server:
  port: 8080

spring:
  application:
    name: open-scholar-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/openscholar
    username: openscholar
    password: openscholar

  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.jdbc: info

openalex:
  base-url: https://api.openalex.org