server:
  port: ${PORT:8080}

spring:
  application:
    name: open-scholar-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/openscholar}
    username: ${SPRING_DATASOURCE_USERNAME:openscholar}
    password: ${SPRING_DATASOURCE_PASSWORD:openscholar}

  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.jdbc: info

openalex:
  base-url: https://api.openalex.org